### ISSUE TITLE
Version collège: espace surveillant

### ISSUE THREAD

**Issue by meaz** [zebobs/Preparation-Documents-PIX-certif#2]
Maintenant, il y a un "Espace Surveillant" avec une procédure un peu différente pour le collège. Les infos ici [https://cloud.pix.fr/s/terBaPyAA3tp64F?dir=undefined&openfile=63551](https://cloud.pix.fr/s/terBaPyAA3tp64F?dir=undefined&openfile=63551)

Ce serait sympa d'ajouter le "Mot de passe de session" sur les feuilles générées.

Ce serait bien aussi de pouvoir choisir entre un fichier html de consignes lycées, et un fichier html de consignes collège, puisque du coup les procédures ne sont plus les mêmes.

**Comment by zebobs** [comment]
Rajouter ce code ne devrait pas présenter de problème. Etant en lycée, je n'ai pas accès à la nouvelle version. Je te recontacte en privé pour essayer de trouver une solution.

Pour le fichier html, je suis preneur d'une modif à intégrer, je ferais le rajout de choix dans le code.

**Comment by meaz** [comment]
ça marche. Pour le html je veux bien m'en occuper dès que le code surveillant sera mis en place afin d'être le plus pertinent possible. Tiens moi au courant.

**Comment by meaz** [comment]
Finalement j'ai fait le fichier de consignes pour le collège, je modifierai au besoin.

**Comment by zebobs** [comment]
C'est mis à jour. Merci pour le document de consignes
